# Sample
# network corrupt
# 'tc qdisc add dev eth0 root netem corrupt 5%'
# network loss
# 'tc qdisc add dev eth0 root netem loss 20% 25%'
# network latency
# 'tc qdisc add dev eth0 root netem delay 2000ms 500ms'
# clean the rules
# 'tc qdisc del dev eth0 root'
# more infomation please check out man netem
'sudo tc qdisc add dev eth0 root netem corrupt 5%'
